[variables]
    PORT = "8080"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = ["composer install --no-dev --no-interaction --prefer-dist", "npm install"]

[phases.build]
cmds = ["npm run prod"]

[start]
cmd = "php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
