[variables]
    # Remove hardcoded PORT to let Railway decide

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = ["composer update --no-dev --no-interaction --prefer-dist", "npm install"]

[phases.build]
cmds = ["npm run prod", "php artisan storage:link"]

[start]
cmd = "php artisan storage:link --force && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan queue:work --sleep=3 --tries=2 --timeout=120 & php artisan serve --host=0.0.0.0 --port=$PORT"
